services:
  demos:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/nrel/demos
    tty: true
    platform: linux/amd64
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - "${DEMOS_CONFIG_PATH:-./configuration/demos_config.toml}:/demos/config.toml:ro"
      - "${DEMOS_DATA_DIR:-./data}:/data"